### ISSUE TITLE
Purpose for the video

### ISSUE THREAD

**Issue by Wowkasu** [FrancescoBorzi/why-I-hate-wow-private-servers#23]
Pirate servers are disliked for three reasons:
1. the players of the official version represent Blizzard at the level of gods, and anything else is considered heresy.
2. The availability of open source, allows it to be used by unscrupulous organizers.
3. Highly skilled developers of emulator, unfortunately, very poorly know the game and introduce unacceptable mechanisms and algorithms, disrupting the gameplay.

Do you want to fight it with video?

**Comment by FrancescoBorzi** [comment]
@Wowkasu I don't want to fight anyone, I just wanted to tell my story so people can get to know it ;)
