### ISSUE TITLE
Incorrect GPL description.

### ISSUE THREAD

**Issue by mabreedlove** [FrancescoBorzi/why-I-hate-wow-private-servers#27]
GPL doesn't say changes have to be released to the public.  What it does say is you have to distribute full source code anytime you distribute.  As private servers do not distribute the software in any form, it isn't applicable.  Even says this in your link:

> In purely private (or internal) use—with no sales and no distribution—the software code may be modified and parts reused without requiring the source code to be released. For sales or distribution, the entire source code needs to be made available to end users, including any code changes and additions—in that case, copyleft is applied to ensure that end users retain the freedoms defined above.

**Comment by Helias** [comment]
![image](https://user-images.githubusercontent.com/519778/148681096-a79b0bfb-f476-4bf0-9ed5-995ee6bc093c.png)

```
GPL requires you to release the modified source code only if you release the modified program. If you've modified a program's source code for personal use, there's no need to release its source code. However, if you make the modified program available to the public, you will have to make the code public too.
```

In a few words: **if you modify an open source software under GPL and you make it available for the public, you need to release the source code (modified) too.**

If you take an open-source core like TrinityCore or AzerothCore, and you modify it on your local machine, that's ok for GPL, but if you open a server with your modifiied code, you need to release it.

**Comment by mabreedlove** [comment]
No, you don't.  It's about distribution, you are not distributing the server to run the program.  It even says there "if you make the modified program available to the public".

What you are suggesting would be ridiculous as there are tons of web services and even your banking software that uses open-source projects and then they would have to release all the code publicly?

**Comment by Helias** [comment]
No, if you take a module open source and use it in your project you don't need to make all your project open source.

But if you take a project or a module that is open source released under GPL license you have to release it open source if you modify it and you let the people to use it.

Source: https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#GPLRequireSourcePostedPublic

**Comment by mabreedlove** [comment]
Exactly, the code runs only on that specific private server.  They are not making the binary available to people.   I feel like there is a disconnect in what you consider distributing.  Distribution is distributing the binary or code so people can run it themselves on their own machines.  No one is distributing anything when it runs on a server and provides services to others.  At no point does the binary code make its way onto someone's system that is playing WoW on it so there is no distribution done.

You can argue they should feel morally compelled to release their changes and thats fine, but this is not a license issue.  Corporations use tons of GPL projects on their servers and don't open everything up.

Hell its even in your own link.

> If I know someone has a copy of a GPL-covered program, can I demand he give me a copy?
> No. The GPL gives him permission to make and redistribute copies of the program if and when he chooses to do so. He also has the right not to redistribute the program, when that is what he chooses.

"Copies of the program"  there is no mention of providing services of it anywhere on that page.

**Comment by Helias** [comment]
A lot of people distribute and sell repacks, binaries, several servers ask the developers to sign an NDA and share for nothing the edits of the source code, this is against the license and a lot of people do it.

Now I have some doubts about the distributing, logically you are taking a source, editing it, and making it available not through binaries but in this case the players are using the content of the binaries through a client, to be honest, I appreciate that you want to be 100% correct and sure about this, I have some doubts about it.

I don't remember if GPLv3 or AGPLv3 has been made to enforce the distribution even in this case, but logically I always think that the goal of GPL is to promote the open-source a bit forcing it, indeed there are other licenses like BSD license that allow you to do what you say, so use the source code of software making it private as Apple or Sony did for their OS without releasing any sources.

**Comment by mabreedlove** [comment]
Actually GPLv3 makes it even more transparent by what they mean by distribution.

> To “convey” a work means any kind of propagation that enables other parties to make or receive copies. Mere interaction with a user through a computer network, with no transfer of a copy, is not conveying.

As for NDA's, if I were to run a server and then contract someone to develop features for it, I could require them to do it under an NDA for me without an GPL license issue.  That much is explicitly stated in their Q&A.  GPL's main goal is to ensure users have rights to modify and distribute software given to them.  If it were reversed, and the server owner received GPL code under NDA from a developer, this is where a license violation would occur.

**Comment by Helias** [comment]
`I don't remember if GPLv3 or AGPLv3 has been made to enforce the distribution even in this case, but logically I always think that the goal of GPL is to promote the open-source a bit forcing it`

AGPLv3 enforce it, indeed on AzerothCore we use AGPLv3.

https://choosealicense.com/licenses/agpl-3.0/

Check "Network use is distribution" and also the license for a short definition of it.

Hope this is clear, let me know if I am missing anything, otherwise we can even close this issue.

```
The GNU General Public License permits making a modified version and
letting the public access it on a server without ever releasing its
source code to the public.

  The GNU Affero General Public License is designed specifically to
ensure that, in such cases, the modified source code becomes available
to the community.  It requires the operator of a network server to
provide the source code of the modified version running there to the
users of that server.  Therefore, public use of a modified version, on
a publicly accessible server, gives the public access to the source
code of the modified version.
```

**Comment by mabreedlove** [comment]
Looks good to me.  Closing.
